apiVersion: v1
kind: Service
metadata:
  name: node-hello-world-service
spec:
  type: LoadBalancer
  selector:
    app: node-hello-world
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
